### ISSUE TITLE
Migration 5.0

### ISSUE THREAD

**Issue by Artur512** [AllanHasegawa/kodein-viewmodel-injector#1]
When do your plan migration to kodein 5.0?

**Comment by AllanHasegawa** [comment]
Soon-ish™ in Blizzard time.

xD

I haven't migrated my projects to Kodein 5.0 yet, so not sure. I'll see the docs this weekend and if the migration is simple, I might just do it.

**Comment by AllanHasegawa** [comment]
Version 0.4.0 now supports Kodein 5.0 🎊
